### ISSUE TITLE
Game Feature Support

### ISSUE THREAD

**Issue by Tezenari** [Phyronnaz/PluginDownloader#3]
## Overview
Add Game Feature support to the Plugin Downloader.

## Requirements
- Add a `Game Feature` option to the `Install Location` combo box.
- Install the Game Feature in the `Project/Plugins/GameFeatures` directory

## For more information regarding Game Features
- [Documentation - Game Features and Modular Gameplay](https://docs.unrealengine.com/5.0/en-US/game-features-and-modular-gameplay-in-unreal-engine/#:~:text=Game%20Features%20and%20Modular%20Gameplay,photoreal%20visuals%20and%20immersive%20experiences.&text=Framework%20for%20creating%20high%2Dfidelity,real%2Dtime%20immersive%203D%20visualization.)
- [Modular Game Feature - What you need to know](https://www.unrealdirective.com/articles/modular-game-features-what-you-need-to-know)

**Comment by Phyronnaz** [comment]
Added! Not sure how well it'll work since the plugin breaks if you try to install a plugin that has dependencies (even if said dependencies are installed).
